import { describe, it } from 'node:test';
import assert from 'node:assert/strict';
import { OllamaClient } from '../src/ollama/client.js';

// ─── extractBlobPath ────────────────────────────────────────────────

describe('OllamaClient.extractBlobPath', () => {
  it('extracts path from a standard modelfile FROM line', () => {
    const modelfile = `# Modelfile generated by "ollama show"
FROM /Users/testuser/.ollama/models/blobs/sha256-7cd4618c1faf8b7233c6c906dac1694b6a47684b37b8895d470ac688520b9c01
TEMPLATE """{{ .System }}"""
PARAMETER temperature 0.7`;
    const result = OllamaClient.extractBlobPath(modelfile);
    assert.equal(result, '/Users/testuser/.ollama/models/blobs/sha256-7cd4618c1faf8b7233c6c906dac1694b6a47684b37b8895d470ac688520b9c01');
  });

  it('returns null for null input', () => {
    assert.equal(OllamaClient.extractBlobPath(null), null);
  });

  it('returns null for empty string', () => {
    assert.equal(OllamaClient.extractBlobPath(''), null);
  });

  it('returns null for undefined input', () => {
    assert.equal(OllamaClient.extractBlobPath(undefined), null);
  });

  it('returns null when no FROM line exists', () => {
    const modelfile = `TEMPLATE """{{ .System }}"""
PARAMETER temperature 0.7`;
    assert.equal(OllamaClient.extractBlobPath(modelfile), null);
  });

  it('returns null when FROM has no sha256 path', () => {
    const modelfile = 'FROM llama3.2:latest';
    assert.equal(OllamaClient.extractBlobPath(modelfile), null);
  });

  it('returns null when FROM path is relative (not absolute)', () => {
    const modelfile = 'FROM models/blobs/sha256-7cd4618c1faf8b7233c6c906dac1694b6a47684b37b8895d470ac688520b9c01';
    assert.equal(OllamaClient.extractBlobPath(modelfile), null);
  });

  it('handles Linux-style paths', () => {
    const modelfile = 'FROM /home/user/.ollama/models/blobs/sha256-abcdef0123456789abcdef0123456789abcdef0123456789abcdef0123456789';
    assert.equal(OllamaClient.extractBlobPath(modelfile), '/home/user/.ollama/models/blobs/sha256-abcdef0123456789abcdef0123456789abcdef0123456789abcdef0123456789');
  });

  it('picks the first FROM line with a sha256 path', () => {
    const modelfile = `FROM /opt/.ollama/models/blobs/sha256-1111111111111111111111111111111111111111111111111111111111111111
FROM /opt/.ollama/models/blobs/sha256-2222222222222222222222222222222222222222222222222222222222222222`;
    assert.equal(OllamaClient.extractBlobPath(modelfile), '/opt/.ollama/models/blobs/sha256-1111111111111111111111111111111111111111111111111111111111111111');
  });

  it('ignores case of FROM keyword', () => {
    const modelfile = 'from /data/.ollama/models/blobs/sha256-aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa';
    assert.equal(OllamaClient.extractBlobPath(modelfile), '/data/.ollama/models/blobs/sha256-aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa');
  });

  it('handles extra whitespace after FROM', () => {
    const modelfile = 'FROM   /data/.ollama/models/blobs/sha256-bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb';
    assert.equal(OllamaClient.extractBlobPath(modelfile), '/data/.ollama/models/blobs/sha256-bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb');
  });

  it('returns null for truncated sha256 hash (less than 64 hex chars)', () => {
    const modelfile = 'FROM /data/.ollama/models/blobs/sha256-abcdef0123456789';
    assert.equal(OllamaClient.extractBlobPath(modelfile), null);
  });
});

// ─── getBlobPath ────────────────────────────────────────────────────

describe('OllamaClient.getBlobPath', () => {
  it('returns blob path from pre-fetched showData', async () => {
    const client = new OllamaClient('http://localhost:11434');
    const showData = {
      modelfile: 'FROM /Users/test/.ollama/models/blobs/sha256-7cd4618c1faf8b7233c6c906dac1694b6a47684b37b8895d470ac688520b9c01',
    };
    const result = await client.getBlobPath('test-model', showData);
    assert.equal(result, '/Users/test/.ollama/models/blobs/sha256-7cd4618c1faf8b7233c6c906dac1694b6a47684b37b8895d470ac688520b9c01');
  });

  it('returns null when showData has no blob path', async () => {
    const client = new OllamaClient('http://localhost:11434');
    const showData = { modelfile: 'FROM llama3.2:latest' };
    const result = await client.getBlobPath('test-model', showData);
    assert.equal(result, null);
  });

  it('returns null when showData is missing modelfile', async () => {
    const client = new OllamaClient('http://localhost:11434');
    const showData = {};
    const result = await client.getBlobPath('test-model', showData);
    assert.equal(result, null);
  });
});

